# -*- coding: utf-8 -*-
"""Rock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u9JM6iadZJ2I6HunAT04G5oAf6GBs0jw
"""

import random

while True:
    choices=["rock","paper","scissors"]
    computer= random.choice(choices)
    player=None

    while player not in choices:
        player=input("rock,paper,or scissors?").lower()

    if player==computer:
       print("computer:",computer)
       print("player:", player)
       print("Tie!!")

    elif player=="rock":
        if computer == "paper":
            print("computer:", computer)
            print("player:", player)
            print("you lose")



        if computer=="scissors":
            print("computer:", computer)
            print("player:", player)
            print("you win")

    elif player=="scissors":
        if computer == "rock":
            print("computer:", computer)
            print("player:", player)
            print("you lose")

        if computer == "paper":
            print("computer:", computer)
            print("player:", player)
            print("you win")


    elif player=="paper":
        if computer=="rock":
            print("computer:", computer)
            print("player:", player)
            print("you win")


        if computer=="scissors":
            print("computer:", computer)
            print("player:", player)
            print("you lose")

    play= input("play again: yes/ no?").lower()
    if play !="yes":
        break

print("bye!!")